### ISSUE TITLE
Add requestedExecutionLevel level=requireAdministrator to the manifest

### ISSUE THREAD

**Issue by b2d** [jrsoftware/issrc#221]
I know that InnoSetup uses some dynamic checking to test if the user has admin rights when "PrivilegesRequired=admin" is set. However for Windows to correctly show the installer icon with an UAC symbol it is additionally required that the manifest file contains:
`<requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>`

Please add this line to the manifest when "PrivilegesRequired=admin" is set, so that the installer symbol is shown correctly by Windows.

**Comment by DeeHants** [comment]
Changing the manifest to that just for the icon will break all of Inno's existing `...AsOriginalUser` support.
This will not be changed.

**Comment by darkguy2008** [comment]
It's not for the icon and this should **not** be closed. I'm having an issue where the compiled installer works if I click Run As Administrator, but if I don't then upon start it throws **ShellExecuteEx failed; Code 1314, A required priviledge is not held by the user.**.

One would expect that by setting ```PrivilegesRequired=admin``` it would do this out-of-the-box without any manifest editing, but it turns out it doesn't do what it describes. At least not in my case.

**Comment by DeeHants** [comment]
@darkguy2008 , that's a different issue. It sounds like your UAC isn't enabled or working properly, or there's a "firewall" or anti malware/virus application that's blocking it.
Either way, as mentioned, the "run as admin" and changing the manifest has other negative side effects, breaking core functionality.
