### ISSUE TITLE
mistake in German translation "Sie" (You) is written as "sie" (they)

### ISSUE THREAD

**Issue by Klaus1189** [jrsoftware/issrc#251]
Only submit an issue if you have already discussed it on the newsgroups first (web-based interface available, see http://www.jrsoftware.org/newsgroups.php). Thanks!

If you ignore these instructions your issue will be closed without notice and your username will be **blocked** from submitting any new issues.

I posted it here:
http://news.jrsoftware.org/read/article.php?id=105642&group=jrsoftware.innosetup#105642

https://github.com/jrsoftware/issrc/blob/master/Files/Languages/German.isl

In line 171:

Now:
Klicken Sie auf "Weiter", wenn sie bereit sind fortzufahren.

How it should be:
Klicken Sie auf "Weiter", wenn Sie bereit sind fortzufahren.

The second "sie" must be written with Capital letter, because now it means "they" but it should be "you", it is a special kind in german.

Please fix this :)

I wish you a Happy New Year

Klaus Luppert

**Comment by martijnlaan** [comment]
Like I e-mailed you, you need to contact the maintainer. Thanks.

**Comment by Klaus1189** [comment]
Why isn't it updated? 
I already emailed the author of the translation and he can't find the string with the error.
I made a screenshot and since then I didn't heard anything. Can I adjust the file by myself?

**Comment by ronaldhoek** [comment]
Hello Klaus,

As Martijn stated (and what I misread in the first place), the translations are the responsibility of the persoon maintaining the translation.

But you can always modify the translation file in your installed version of InnoSetup (\Inno Setup 5\Languages). When recompiling your iss project, you should see the modification.

**Comment by Klaus1189** [comment]
Thanks for your reply, but it is really a big issue, that such a small issue (!!!) can't be fixed. 

As I already wrote, I emailed Peter Stadler that mistake, but he couldn't find it. 
Then I sent him a screenshot with an arrow pointing to the mistake. But now I don't hear anything from him.

I offer you my skills for the german translation.
I already translate MPC-BE and this string can't be translated there because it must be corrected here.
The root of the problem.

What is wrong in this project ... ? ... ...

**Comment by ajtruckle** [comment]
Just tell Martin you want to take over. But I agree. I have put messages in the newsgroup and no answer. I think maybe we should expand to using this media as a user resource and not make hard and fast rules. But I cooperate as they wish. Either way I got no answer to my query.

The good thing here is we are notified. We are not notified in the web portal.

Andy

Sent from my iPhone

On 29 Jan 2018, at 16:46, Klaus1189 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your reply, but it is really a big issue, that such a small issue (!!!) can't be fixed.

As I already wrote, I emailed Peter Stadler that mistake, but he couldn't find it.
Then I sent him a screenshot with an arrow pointing to the mistake. But now I don't hear anything from him.

I offer you my skills for the german translation.
I already translate MPC-BE and this string can't be translated there because it must be corrected here.
The root of the problem.

What is wrong in this project ... ? ... ...

**Comment by ajtruckle** [comment]
So you mentioned:

> Now:
> Klicken Sie auf "Weiter", wenn sie bereit sind fortzufahren.

> How it should be:
> Klicken Sie auf "Weiter", wenn Sie bereit sind fortzufahren.
> 
> The second "sie" must be written with Capital letter, because now it means "they" but it should be "you", it is a special kind in german.

In my file for line 171:

SelectComponentsLabel2=Wählen Sie die Komponenten aus, die Sie installieren möchten. Klicken Sie auf "Weiter", wenn sie bereit sind fortzufahren.

I have the latest build. And you say it should be:

SelectComponentsLabel2=Wählen Sie die Komponenten aus, die Sie installieren möchten. Klicken Sie auf "Weiter", wenn Sie bereit sind fortzufahren.

So, from my point of view the translation is not up to date. The file on the website is not up to date either:

https://raw.githubusercontent.com/jrsoftware/issrc/master/Files/Languages/German.isl

So perhaps Martin can get involved because clearly something is not right. I am sure all of us appreciate you taking the time to bring these things known. It seems a quick issue to resolve. :)

**Comment by Klaus1189** [comment]
definitely :)

**Comment by ajtruckle** [comment]
It is interesting if you look here:


http://news.jrsoftware.org/read/article.php?id=2502&group=jrsoftware.innosetup.translations#2502


The original author made changes to the translation in July 2017. The latest installer and website file is 2015. So I don't know where his submitted file went to. He may have made the changes, submitted it and it not get deployed.


It would explain.


Andrew


________________________________

**Comment by ajtruckle** [comment]
But this file:

https://github.com/jrsoftware/issrc/blob/master/Files/Languages/German.isl

WAS updated 6 months ago. Uyet line 171 is still not with capital S..... But this newer file is not available in any installer yet ...

**Comment by Klaus1189** [comment]
very strange

I translate MPC-BE:
https://sourceforge.net/p/mpcbe/code/commit_browser
https://yadi.sk/d/hlf1lfC8mKU58

I found the mistake in its installer.

**Comment by martijnlaan** [comment]
I will email Peter myself and if he does not reply within 3 weeks you can take over as a maintainer. Being a maintainer does require you to follow the (simple) instructions.

**Comment by Klaus1189** [comment]
ok, thanks
